- conf/locale/ar/LC_MESSAGES/django.po
- conf/locale/he/LC_MESSAGES/django.po
- media/css/global/main.css
- media/css/minimalistic_language_picker.css
- media/js/minimalistic_language_picker.js
- signbank/context_processors.py
- signbank/dictionary/templates/dictionary/admin_gloss_list.html
- signbank/dictionary/templates/dictionary/admin_minimalpairs_list.html
- signbank/dictionary/translate_choice_list.py
- signbank/settings/server_specific/default.py
- signbank/settings/server_specific/global_sb_new_aj.py
- templates/global-templates/baselayout.html
- templates/global-templates/menu.html
- templates/global-templates/tooltip.html
In this pull request:
* #696 Added two new interface languages: Hebrew and Arabic 
* #696 Wired the language picker to the interface languages in the settings (no longer dynamic) 
* #696 Removed the flags and animations from the language picker
* #703 Unified tooltip html to single location, made it translatable
Points of doubt:
* I added this setting, which populates how the languages are called in the language picker:
``
#Short (abbreviated) version of how language users call their language, to be used in the language picker
INTERFACE_LANGUAGE_SHORT_NAMES = ['EN','NL','官话','עִברִית','عربى'] 
``
A prettier solution, I think, would be to add this to the language objects in the Django admin, as this is where we specify how languages are called in other languages anyway. However, because …
> New interface languages and language picker

- requirements.txt
- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/templates/dictionary/admin_lemma_list.html
- signbank/dictionary/templates/dictionary/search_result_bar.html
- signbank/dictionary/tests.py
- signbank/tools.py
This branch has the following:
- allows deletion of lemma's that have no glosses, along with their related translation objects. This functionality is offered on the Lemma List page. There is a confirm dialog. The deletion only applies to lemma's without glosses that are in the queried results.
- adjusts the order during export of minimal pairs to CSV to account for large files. The minimal pairs are computed before generation of the file is started. Previously, the file was created and then written row by row as the minimal pairs were computed. While the computation time is still slow, 15 minutes for NGT, it does not timeout/crash any more, at least on my local server.
-  includes a bugfix with the links in the results scroll bar
- adds magic to the python virtual environment requirements
> Lemmas without glosses 733 and minimalpairs to CSV 743

- signbank/dictionary/templates/dictionary/dataset_detail.html
This issue adds a link to the corpus overview template for a dataset.
Because the url for the template relies on the dataset id, this is linked to via the Dataset Detail View.
This link is not shown to anonymous users.
> Corpus Overview via Dataset Detail

- signbank/dictionary/templates/dictionary/import_csv_create.html
- signbank/dictionary/templates/dictionary/import_csv_update.html
- signbank/dictionary/templates/dictionary/import_csv_update_lemmas.html
- signbank/dictionary/views.py
This branch adds user friendly import of csv files as discussed in #761.
Empty rows are ignored rather than complained about.
Non-UTF-8 encoded files are given an informative error message rather than crashing. (See screenshot in the issue.)
Files that do not end in csv are not allowed to be chosen by the browser input dialog.
If a user has changed the extension of a non-csv file to csv, it is caught in the python code and an error message displayed rather than crashing.
Delimiters can be chosen on the` Import CSV Update` and `Import CSV Lemma` templates.
This was previously only on the `Import CSV Create` template as it was assumed users would obtain an initial csv from exporting.
> Csv user friendly

- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/admin_dataset_manager.html
- signbank/dictionary/templates/dictionary/dataset_frequency.html
- signbank/dictionary/tests.py
- signbank/dictionary/update.py
- signbank/dictionary/urls.py
- signbank/frequency.py
- signbank/urls.py
This branch adds submap functionality for corpora eaf files. See Issue #793 for screenshots.
The Dataset Manager page allows importing eaf files or folders of eaf files. This is indicated with a toggle in the interface.
The Corpus Overview page has been extended with a panel list of uploaded eaf files for the documents.
Duplicates are highlighted in red.
Already processed files are highlighted in blue.
Because duplicate eaf files are a problem, because frequencies would be processed twice, this is considered an error.
Functionality is provided to remove the unwanted eaf files.
Once duplicates have been removed, the user can refresh the documents as before.
Modals have been added as an extra layer. A confirm dialogue is shown for removing files.
A helpful message is shown before the user …
> Issue #793: Added submap functionality for corpus files.

- signbank/dictionary/templates/dictionary/import_media.html
- signbank/dictionary/views.py
- signbank/tools.py
This implements user friendly feedback on importing videos from folders.
To eliminate extraneous feedback about other datasets, it is limited to the selected datasets.
A template view table shows the status of imported videos for the datasets and their language folders, as described in #799.
> Issue #799: video import feedback per dataset in table view

- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/templates/dictionary/gloss_detail_preview.html
- signbank/dictionary/templates/dictionary/morpheme_detail.html
- signbank/dictionary/tests.py
- signbank/dictionary/update.py
- signbank/dictionary/views.py
This issue effectively renames a constant defined in forms to match the hard coded usages of it.
Also the reverse is done as both identifiers were being used.
keywords_  => keyword_
Because of the numerous usages, it was easier to modify things to match up with the "keyword_" identifier.
> Issue #801: Repaired search field translation equivalents.

- signbank/dictionary/views.py
This modifies the three Import CSV functions to use the Delimiter in parsing the Header row.
The code has been enhanced to do the things related to parsing the CSV file at the front, so that the Import File Form is shown to the user. Any errors related to this are shown as messages in the template.
Namely, if the wrong delimiter is chosen, or the encoding is wrong, or a required column is missing, these are all shown at the start.
This essentially repairs a bug with Apple formatted CSV files not being imported correctly.
> Csv user friendly repairs to delimiter parsing

- signbank/dictionary/update.py
- signbank/registration/templates/user_profile.html
- signbank/urls.py
This branch adds a button to user profile to extend the expiry date of their account.
The button is shown when there are less than 60 days remaining.
Pushing the button results in extending the expiry by 6 months.
This is done without need for the Admin.
> Issue #648: Extend Expiry facility added to User Profile.

- signbank/dictionary/templates/dictionary/gloss_revision_history.html
- signbank/dictionary/translate_choice_list.py
- signbank/dictionary/update.py
- signbank/dictionary/views.py
This implements issue #800.
The bug was located in saving to GlossRevision when the new value is None (aka Neutral).
This has been repaired by saving the human readable value Neutral in the history.
> Issue #800: Setting weakdrop back to Neutral; #760: Tags in GlossRevision; Refine Display

- signbank/dictionary/tests.py
The test did not run because the gloss video folder was deleted when the test class was done running.
Now the folder is created before a single test and after that test it is also deleted and that seems to fix the problem.
I am not sure what the actual problem was, another test probably used the folder when it was removed.
There are still 4 failures and errors but i believe those have nothing to do with this problem (but again not sure)
Linked this branch to issue 882 Running tests in production container doesn't work
> Fixed database test by changing gloss api test setup method

- signbank/dictionary/adminviews.py
- signbank/dictionary/templates/dictionary/glosslist_headerrow.html
The 'x' button and colors of active sorting arrows didn't show
> Undo sortorder of searching signs fixed #544

- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/find_and_save_variants.html
- signbank/dictionary/update.py
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
This issue revises the `find_and_save_variants` code in `views.py`.
- accommodates datasets and selected datasets
- non Latin languages (e.g., Japanese)
- makes use of a template (used to have hard-coded html)
- identifies focus glosses with annotations of pattern ending in -A, -B, ...
- displays a table showing other glosses that end in a different letter that are not related in some other way
- does not update anything, merely displays the patterns it finds (it used to save variants as new relations)
The code for `get_stems` (the pattern before the suffix) has been flattened out in order to work with non-Latin character sets.
The list comprehension did not work on Japanese.
See screenshots in the issue.
The code for actually saving the found variants has been commented. This can be …
> Issue #876: Updated code for finding variants.

- signbank/dictionary/tests.py
- signbank/dictionary/views.py
Hi all, 
I created this draft pull request because I added the gloss id to the data that returns but I can't test if this change breaks anything because I do not have the correct database anymore to run Signbank locally.
I spoke with Susan last week and she said I could get the latest database from the applejack server but I do not have permission to access the server.
I updated my own unit test and because it is a really small change I don't think anything else will break but like mentioned before I have not tested it.
How can I get a copy of the new database or can someone else test it let me know if things break?
> App endpoints

- signbank/dictionary/update.py
Small fix: if sentences already existed before the last migration they have the default order 1 so this gave a problem when moving one up or down. Instead they first need to be given the right order number and then can be moved just fine.
> Fix for ordering of sentences that already existed

- signbank/dictionary/adminviews.py
- signbank/dictionary/context_data.py
- signbank/dictionary/field_choices.py
- signbank/dictionary/forms.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/admin_gloss_list.html
- signbank/dictionary/templates/dictionary/admin_handshape_list.html
- signbank/dictionary/templates/dictionary/admin_morpheme_list.html
- signbank/dictionary/templates/dictionary/admin_senses_list.html
- signbank/dictionary/templatetags/annotation_idgloss_translation.py
- signbank/dictionary/translate_choice_list.py
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
- signbank/query_parameters.py
- signbank/settings/server_specific/default.py
- signbank/urls.py
- This fixes the form reset code and makes sure the search parameters just done are still visible in the search form.
- The "yes/no" choices have become translated for morpheme search and the values homogenized.
- Obsolete Django syntax (the `u'`) has been removed from `forms.py`.
- Processing of the "get" parameters has been moved to a separate function to reduce the code in the get_queryset
- To allow sharing of the search form between the get_context_data and the get_queryset, the form has been made a self field of MorphemeListView.
- This allows the code that processes the "get" queryset to receive the search form.
- In order to process the "search form" fields by iterating over the search form, the language fields have been made fields instead of attributes.
> ClearForm Reset and Streamline Handshapes and Morphemes

- signbank/dictionary/admin.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/related_objects.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/update.py
- signbank/settings/server_specific/default.py
Information has been added to the modal for Delete this sign.
At the moment, I commented out the actual gloss.delete() in update.py
Do we want to prevent the user from deleting the gloss if it's related to other objects?
> Show warning on delete sign in gloss edit view if references other glosses

- signbank/dictionary/templates/dictionary/gloss_detail.html
This is a super small thing, but I'd like a thumbs up from at least one of you before I merge to master. 
The context:
* ASL signbank doesn't use our dataset functionality, as they have only 1
* As a consequence, they also have no 'translation language' for 'annotation ID gloss'
* This resulted in weird empty parentheses in the gloss detail view
> Don't show annotation language parentheses by default

- signbank/dictionary/adminviews.py
- signbank/dictionary/related_objects.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/video/models.py
A button has been added to GlossDetailView to allow moving a gloss to a different dataset. #1119 
This involved updating the lemma field dataset to the new dataset.
To maintain consistency, the dataset of the related glosses (via relations or morphology) are also changed.
To do the morphology, reverse morphology is also retrieved in related objects.
For example, gloss Ijsbeer = Ijs + beer.
If any of these glosses is moved, the others also need to be moved.
This is done in an atomic transaction.
The videos and images of the gloss(es) are also moved to the new dataset.
This is done using a signal. (As for other updates.)
At the moment, there are checks that the user is a superuser in order to do this.
Both datasets must be selected.
The existence of the gloss already in the target dataset …
> Move button to switch dataset of gloss

- signbank/dictionary/adminviews.py
- signbank/dictionary/related_objects.py
- signbank/dictionary/templates/dictionary/morpheme_detail.html
- signbank/dictionary/update.py
- signbank/settings/server_specific/default.py
that is referenced by glosses
Added a setting to guard morpheme delete. Default is True since they exist but are in limited use so far.
> Show warning when attempting to delete a morpheme

- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/admin_lemma_list.html
- signbank/dictionary/tests.py
Moved annotated query to model method to count number of glosses. Removed extra annotated queryset that could not be paginated correctly. Now it uses object_list and calls the new num_gloss method in the view.
BACKGROUND
There used to be two get_queryset methods in the LemmaListView. One provided an annotation column with the number of glosses for the lemma.
The pagination did not work for this setup and all the lemmas kept appearing on Page 1, and every page thereafter.
To repair this, the "num_gloss" was put in a LemmaIdgloss method instead of being used as an annotation on the queryset.
The two queryset methods were merged in a sense into a single method.
The code is a bit obtuse. The actual pagination links in the template are difficult to read.
This branch is deployed on signbank-dev …
> #1198: Rewrote queryset code of LemmaListView

- signbank/abstract_machine.py
- signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api.html
- signbank/dictionary/views.py
- signbank/gloss_update.py
@susanodd When given input for field 'senses', all existing ones are removed from the gloss (for every language) and deleted (if not in another gloss) and the new senses are created. So it doesn't check for each translation/keyword separately. 
Input is in the form of 'senses': '{"en": [["s1w1", "s1w2"],["s2w1"]], "nl":[["s1w1"],["s2w1", "s2w1"]]}"
Can you check if you agree with this implementation?
> Update senses field added to update gloss API #1202

- signbank/abstract_machine.py
- signbank/api_interface.py
- signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api.html
- signbank/dictionary/views.py
- signbank/gloss_update.py
This is live on signbank-dev !!!!
This checks for database conflicts before allowing to update.
- already used annotations or lemmas for the dataset and language
- shared lemmas cannot be updated
Also for the API update, modification of strings stored in Gloss Revision History for Senses.
The history has some quirks because the senses updates are done as a whole.
This has been done using a loop over the "before" senses and in turn the "after" senses, using the `__str__` method of the Sense class and a join using '`|||`' to separate. These are both modular, but the strings are stored in the history when saved.
The update to the lemma and annotation fields includes mappings between three different "labels" all available in interface languages.
- the display column human-readable header …
> API update lemma and annotation fields

- signbank/dictionary/views.py
Debugging together with Divya, we've figured out that setting the guardian permission to `view_dataset` always results in just `[NGT]`, even though she has view permission on several datasets (which I can verify). If I make it `change_dataset`, like it used to be, the problem goes away. 
Divya has a deadline, so I propose:
* Rollback the situation, so she continue her work AND
* Figure out what's really happening here (is the permission named differently? is there something else happening with view permissions?)
If bullet point 2 takes too long, we can make it a separate issue.
> Dictionary info endpoint: permission change rollback

- signbank/dictionary/management/commands/add_user_affiliation_to_glosses.py
Purpose for when user affiliation was missing and has been added recently
This command adds the users affiliation to the glosses created by the user.
This fixes an omission for automatically adding the Radboud affiliation.
Some Radboud users did not have an affiliation assigned.
The command can be applied to add the affiliation for users after being assigned an affiliation.
> Give feedback on adding affiliation to glosses

- signbank/abstract_machine.py
- signbank/api_interface.py
- signbank/api_token.py
- signbank/dictionary/views.py
- signbank/gloss_morphology_update.py
- signbank/gloss_update.py
I tried to create a solution that is elegant and reusable.
> fix: Add a decorator to put API user in request #1278

- signbank/api_interface.py
- signbank/dictionary/adminviews.py
- signbank/manage_videos.py
- signbank/zip_interface.py
in error message feedback
- gloss not in selected datasets => reports dataset gloss is in
- import zipped video archive => does not check h264
- mport zipped video archive => same dictionary for branches in json result
- mport zipped video archive => if video file overwrite existing fails, report error and do not return video url (since not uploaded)
> #1331: Improve error reporting (phase 1)

- media/js/drag_drop_files.js
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/update.py
- signbank/dictionary/views.py
- signbank/gloss_update.py
- signbank/video/admin.py
- signbank/video/forms.py
- signbank/video/models.py
- signbank/video/urls.py
- signbank/video/views.py
This fixes some bugs going on here and there. Discovered during testing.
This branch cleans up some messy code and adds lots of log messages (prefaced by settings check)
Motivated by #1354, #1358
Added print logs of video paths when DEBUG_VIDEOS is True
Some extra checks/conversions/explicit making of implicit parameters
OTHER STUFF TO CHECK (subsequent branch)
- Add checks that there are not multiple GlossVideo objects if a file has not been deleted or moved 
- (because of "pass" operations in except at OS level a file may not have been moved/deleted and an object may not have been deleted)
- The control flow is difficult to follow because of code sharing and signals from saves in other models.
- Parameter `upload_to` may be frozen when the object is created. This used to just be …
> File writing video path bugs avoidance

- signbank/settings/server_specific/default.py
- signbank/settings/server_specific/global_sb_new_aj.py
- signbank/tools.py
@susanodd @Woseseltops @vanlummelhuizen question: MPI want to only have senses in the ECV gloss descriptions, not phonology or other information. Would this be ok to put that in the default settings? Does anyone else use these ECV files?
> Only add senses to ecv descriptions, not phonology #1325

- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_row.html
- signbank/video/models.py
Remove an existing gloss video file that does not have an object; lazy creation of gloss video object if file does not have it.
Solution thought up by @Jetske and @susanodd when looking at the video storage.
This patch includes two parts.
- if a Gloss Detail page is visited and there is a video file but there is no GlossVideo object pointing to it, an object is created for it.
- if a new video is being uploaded but there already exists a file with this name, but no GlossVideo object, the file is deleted so that the new file can have a correct path, without the 7-char code added to it.
Based on recent video creations, this is happening, so this is necessary.
If you want to try this out on your local signbank, then 
- set DEBUG_VIDEOS to True.
- Then for a particular gloss, remove its …
> #1356: Patch to prevent 7-char sequence and missing objects

- signbank/dataset_checks.py
- signbank/dictionary/management/commands/rename_backup_gloss_videos.py
This was easier said than done. I revised the code yet again to test more things.
Ter informatie: if you do `str(glosssvideo.videofile)` versus `str(glossvideo.videofile.name)` the first is the relative path and the second is just the filename
(But this is inconsistent, there are counter-examples in the code. This may have something to do with evolution of signbank storage. It also has something to do with whether Python paths are created.)
> #1377: repairs to renaming backup files command

- signbank/dictionary/adminviews.py
This change is trivial.
- @Woseseltops this is on signbank-susan now.
- You do a Search on the dataset (NGT since that's what we're testing)
- Then go to `Analysis -> Split Up Senses`  (it shows them for the most recent query results)
- The "browser debug window" has trouble showing all the nodes!!!!
- But it does indeed work!!!
- But I suspect it might not be showing all the results????
- In the python code, I set it to display 500 results per page.
- But there are only 2 pages shown.
- Can you experiment with this yourself to see what the browser is doing? I'm using Firefox so I can't test it for Windows
- I also don't know whether Firefox is just throwing stuff away because it's too much???
> #1400: Unlimited retrieval and 500 glosses per page on Split Senses

- signbank/dictionary/templates/dictionary/gloss_detail.html
The disadvantage of this modification is that the images are generated every time the user clicks on Choose Still.
This is because the operation needs to clean up after itself in case the user has uploaded a different video, etc.
If the user decides to choose a still image, but does not actually select any image (chooses "dismiss") then the images are not cleaned up from the server.
> #1392: Removed another button from Choose Still

- signbank/dictionary/adminviews.py
- signbank/video/convertvideo.py
I tried this with different lengths of videos. Some videos are really short.
This works now.
> #1392: Only show nine still images from video.

- signbank/video/models.py
- signbank/video/views.py
Makes it possible to upload .eaf files with different tier names
closes #1399
> Upload different format .eaf files #1399

- signbank/settings/base.py
This prevents screen dumps of data structures if a command fails
> #1436: Set DEBUG to False in base.py settings

- signbank/dictionary/views.py
This is available by selecting development server `signbank-dev` Swagger
- `dictionary/package/`
- `dictionary/info/`
Signbank-dev has a database from January 20.
> #1408: Repairs to API adding BadRequests responses to endpoints

- signbank/dictionary/admin.py
This is because of database constraints and related objects. The normal signbank interface should be used, not the Admin.
This solves a bug reported in #1270. (https://github.com/Signbank/Global-signbank/issues/1270#issuecomment-2514473974)
It's not allowed to created senses or glosses in the admin because of database constraints. This needs to be done in the signbank interface. This is moreso on an empty database.
This will be put on a development server when one becomes free, if desired.
> 1413: Removed Admin buttons where operation is not allowed.

- signbank/api_interface.py
- signbank/dictionary/urls.py
A new endpoint for poster images as requested by @rem0g . 
The endpoint can be called like this (the test environment will be online for 2 weeks, you can use this temperorary token to test if you want):
```python
import requests
url = 'http://52.57.57.71/dictionary/api_update_gloss/4483/image'
image_file_path = 'VLINDERS-IN-DE-BUIK-B-48960.png'
headers = {'Authorization': f'Bearer JZnWi1BoQvtEmzcL'}
payload = {'File': open(image_file_path, mode='rb')}
response = requests.post(url, files=payload, headers=headers)
print(response.status_code)
print(response.text)
```
When working on this, I created #1475 and #1476, tasks to be picked up once this is live.
> Added citation image API endpoint

- signbank/dictionary/templates/dictionary/edit_annotated_sentence.html
Fix for #1511 by using `protected_media` instead of the url from the `eaffile` field.
> fix: Make EAF file of annotated video use protected_media #1511

- signbank/dictionary/admin.py
- signbank/dictionary/gloss_revision.py
- signbank/dictionary/templates/dictionary/gloss_revision_history.html
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
- Fixed display to show revision history in the current interface language being used, including the field values (objects in the revision history have strings for everything, these are in the interface language being used at the time that they were stored)
- Template command to clean up the revision history (removes empty entries, removes repeated duplicates leaving one)
This is on signbank-dev.
Try searching on "recently added glosses", then look at their Revision History (the glosses with lots of empty stuff in the history), then press "Clean Up". Presto! This is totally awesome!
Note, pull request #1485 is also needed, since it stops storing these empty things in the revision history.
> #1477: Template command to cleanup revision history

- conf/locale/nl/LC_MESSAGES/django.po
- signbank/api_interface.py
- signbank/registration/locale/nl/LC_MESSAGES/django.po
- Side effect (this issue makes changes of other issue): File api_interface.py (See changed files)
I needed to reorder the import of `gettext` because it wasn't being recognised as imported by PyCharm type-checking.
I also removed the greyed out imports that are not used according to PyCharm. The import of `zipfile` also needed to be moved below other imports for it to be "not grey".
- How to translate "you" ?
Both forms are used in the translations. (Most of the time because it's catch phrases used in computer jargon.) Since there are thousands of translations, I'm just going to leave it as is.
> 1518 update the po files to include recent interface changes

- signbank/csv_interface.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/tests.py
- signbank/dictionary/views.py
- signbank/gloss_update.py
- signbank/query_parameters.py
- signbank/settings/server_specific/default.py
Many small bug fixes. Bugs found during trial and error of all the different fields
- Code for multilingual gloss update translation code #1484
- Renamed functions to make it clear what is being done. CODE IMPROVEMENT
- Added status code 400 to error branches to make sure failure of the operation is observed by caller. CODE IMPROVEMENT
- Fail for transaction error on save BUG FIX
- Repaired code that translated API input json "left hand side". BUG FIX
- _("Senses") translation to Dutch is hard-coded, since it does not work to retrieve the verbose name from the Gloss field. Unknown why, maybe because it's a verbose name on a relation. This used to work. Maybe Django updates.
- Normalise Boolean values (this was not working at all, bug was not reported) BUG FIX
- Only update those fields …
> BUG FIXES gloss update API -- stop putting empty things in revision history

- signbank/dataset_operations.py
- signbank/dictionary/dataset_views.py
- signbank/dictionary/forms.py
- signbank/dictionary/templates/dictionary/admin_dataset_manager.html
- signbank/dictionary/templates/dictionary/admin_dataset_videos_list.html
- signbank/dictionary/urls.py
- signbank/settings/base.py
- signbank/urls.py
- This pull request sets up a Template, List View, and Search Form for Gloss Videos of a Dataset
- This is completed. It's on signbank-dev.
- To navigate to the page, it's linked to under Manage Datasets -> (Dataset) Manage Video Storage
https://signbank-dev.cls.ru.nl/datasets/glossvideos/5
- The new page replaces the existing page.
<details>
(The old template file, class, and url have not been removed yet, they are just unnavigable now. If you type in the former url you can still compare the old page to the new, which is now linked to as described above.)
</details>
- New: Search functionality
- New: Delete buttons for cleaning up excessive backup files. (Moves them to trash folder as is done in ADMIN.) (Note, when you try this on the development server, it merely deletes the objects if …
> #1406: Gloss Videos List View, Search Form, template

- signbank/dictionary/adminviews.py
- signbank/dictionary/context_data_gloss.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/update.py
- signbank/video/models.py
I have implemented new model methods to accomplish what is needed. The javascript in the detail view has been parameterized with the offset of the NME video (collection) parameters.
Everything is implemented except a "full screen" button. (Jetske wrote the existing full screen code for normal videos.)
This issue is about the display of NME perspective videos.  As a side effect, I had to change the "NME update" because the descriptions and offset fields are no longer visible for the perspective objects in the template.
Another side effect is the "package". It needs to code explicitly include the perspective videos for the NME videos.
1. Added perspective to NME video `__str__` method
2. Added dictionary gloss method to retrieve NME lookup dictionary per NME offset to group the perspectives …
> #1526: Display viewer for NME videos with perspective

- docs/signbank-api.json
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
In confirming that the Swagger code works properly, this issue was encountered #1572
Now all the Swagger urls accept the bearer token. If the token is missing, they do the previous Swagger behaviour
I checked the Swagger code on my local computer using a symbolic link to the Swagger docs folder in order to run the local changes in the browser and have it be run on the real server.
This issue #1573 is also addressed in this pull request.
> Added Swagger for NL urls for retrieval, creation, update

- media/js/gloss_edit_color.js
- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/update.py
coerce Boolean internal values to strings using method to display, explicit use of internal Booleans in choice list for update
I'm not sure when the bug arose. It looks like it was using different choice lists. In the template, numbers were being used, and the (old) values were the actual NullBoolean internal values.
I added a coercion to make the internal values become strings (but using 'None' instead of it ending up the same as False for None values)
I modified the template to test on these strings rather than the internal "value" (NullBoolean).
Likewise, the update processing converts the internal (stored) values to numbers (corresponding to the choice list in the form)
The implementation of the editable code uses choice lists with numerical domains. Probably this went wrong since it …
> BUG FIX: Fixed weakdrop weakprop, made editable mimic list code

- signbank/dictionary/adminviews.py
- signbank/dictionary/context_data.py
- signbank/dictionary/templates/dictionary/admin_annotatedgloss_list.html
- signbank/dictionary/templates/dictionary/admin_annotatedsentence_list.html
- signbank/dictionary/templates/dictionary/admin_batch_edit_senses.html
- signbank/dictionary/templates/dictionary/admin_batch_edit_view.html
- signbank/dictionary/templates/dictionary/admin_gloss_list.html
- signbank/dictionary/templates/dictionary/admin_lemma_list.html
- signbank/dictionary/templates/dictionary/admin_minimalpairs_list.html
- signbank/dictionary/templates/dictionary/admin_morpheme_list.html
- signbank/dictionary/templates/dictionary/admin_senses_list.html
- signbank/dictionary/templates/dictionary/admin_toggle_view.html
The [`json_script` template filter](https://docs.djangoproject.com/en/5.2/ref/templates/builtins/#std-templatefilter-json_script) solves the XSS vulnerability in a concise and elegant way. It puts potential dangerous strings on the page in a safe way. With this filter it is not necessary to encode/escape the string(s) in another way, whether on the front-end with Javascript or on the back-end somewhere in Python. The result is that the string entered by the user is kept in the input box unchanged, while still preventing XSS.
> 987 xss attempt 2
