- signbank/dictionary/tests.py
Revised tests.py to account for removed duplicate field choices.
> Issue #697: Fixed Field Choice Test.

- signbank/dictionary/admin.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/templates/dictionary/gloss_detail_preview.html
- signbank/dictionary/templates/dictionary/morpheme_detail.html
- signbank/dictionary/update.py
Modifications to Other Media section of Gloss Detail View.
Checks for existence of file and greys out download if something is wrong.
Upload quotes the input filename if necessary and uses that instead of the original filename on the user's computer.
Upload checks that the file type is okay.
> Issue #735: Other media files Gloss/Morpheme view/upload.

- media/css/custom_admin.css
- signbank/dictionary/admin.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/templates/dictionary/dataset_detail.html
- signbank/registration/forms.py
- signbank/registration/templates/registration/registration_form.html
- signbank/registration/views.py
This branch includes a simple change (#682) which adds a button to the Dataset Detail page for an anonymous user to request access. This button goes to the Registration page, where that Dataset is preselected in the choice of datasets.
The other issue in this branch is #739.
This includes numerous changes to Admin (!) that restrict some of the functionality that was causing extreme slowness (in Admin).
This is primarily in Gloss administration, as shown in #739.
Some additional Inline classes have been filled in because other models were also extremely slow.
LemmaIdgloss now has administration. But this is limited to only adding translations if they are missing for the dataset.
If the dataset is missing on a lemma, this can not (yet) be "fixed" (i.e., the Dataset field, if it is not set, …
> Admin issues 739 682

- signbank/dictionary/models.py
This branch makes major revisions to the computation of minimal pairs to improve efficiency.
> Issue #743: Efficiency revisions to minimal pairs computation.

- signbank/registration/forms.py
- signbank/registration/models.py
- signbank/registration/templates/registration/registration_complete.html
- signbank/registration/templates/registration/registration_form.html
- signbank/registration/views.py
- templates/global-templates/loginform.html
- templates/global-templates/menu.html
This branch fixes the registration of new users.
Some legacy code has been removed.
> Issue #755: Fixed Registration.

- signbank/dictionary/templates/dictionary/admin_dataset_manager.html
> Dataset Manager View: Changed order of columns.

- signbank/context_processors.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/templates/dictionary/admin_dataset_list.html
- signbank/dictionary/templates/dictionary/admin_dataset_select_list.html
- signbank/dictionary/update.py
- signbank/tools.py
- signbank/urls.py
- templates/global-templates/menu.html
This branch implements issues #780 and #781.
It sets up a session variable for the selected datasets for anonymous users.
> Select datasets for anonymous users

- signbank/registration/__init__.py
This fixes the login authentication to use the username not the email address.
> Issue #788: Fixed multiple objects found on login.

- conf/locale/nl/LC_MESSAGES/django.po
Resolved fuzzy translations in the NL po file.
> Translations fuzzy

- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/templates/dictionary/morpheme_detail.html
> Hide empty semantics fields in Morpheme Detail and Gloss Detail views

- signbank/dictionary/adminviews.py
In the Manage Datasets View, granting change permission to a user now puts the user in Group Editor if they are not in this group yet. Similarly, revoking change permission and leaving no datasets the user can change removes the user from Group Editor.
> Issue #623: Grant change dataset puts user in Group Editor.

- signbank/dictionary/adminviews.py
This solves a bug in the typeahead for morphemes in the Search by Morphology panel of List View.
> Issue #492: Typeahead for morphemes in Search by Morphology.

- media/js/drag_drop_files.js
The file size was not limited for dropping files and through the normal input file field, so this is added here
> Max file size for drag&drop, #886

- requirements.txt
- signbank/dictionary/models.py
- signbank/video/convertvideo.py
- signbank/video/models.py
Please run this to test, as my database is not up to date!
> Matroska files converted to mp4 issue #886

- signbank/dictionary/models.py
For some video's it gives an ffmpeg error. It should just continue running after that.
> Quick fix for when converting does not work #886

- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/import_csv_update.html
- signbank/dictionary/update.py
- signbank/dictionary/views.py
- signbank/tools.py
Rewriting of the Import CSV Update of Notes and Tags.
- Fixed some glitches related to the representation and parsing of notes in the csv.
- Added toggles to allow removal of tags and notes.
- Removed some variables that were outside of the functions (aftermath of using new Field Choices that they need to be dynamic.)
> Csv interface notes and tags improvement

- signbank/dictionary/adminviews.py
- signbank/dictionary/templates/dictionary/admin_query_list.html
- signbank/search_history.py
Modal in the Query View to show if specific parameters are not yet implemented to save.
> Search history notification if parameters not yet available

- signbank/dictionary/adminviews.py
- signbank/dictionary/update.py
- signbank/tools.py
This combined with the patch outlined in #946 which renames the new permission.
> Changes to accommodate can_view_dataset as well as view_dataset

- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/update.py
- signbank/dictionary/views.py
- signbank/tools.py
Fixed sequential morphology FieldChoice role. Removed obsolete code, fixed iso spacing. Strip text fields to remove hidden tabs.
> CSV Import: Fixed Django/Python bug html.unescape; Fixed Notes parsing.

- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/tagviews.py
- signbank/dictionary/templates/dictionary/admin_gloss_list.html
- signbank/dictionary/templates/dictionary/admin_morpheme_list.html
- signbank/dictionary/templates/dictionary/gloss_row.html
- signbank/query_parameters.py
- signbank/search_history.py
Made tag choices dynamic in forms. Adjusted query and search history code to accommodate.
Made tags in Gloss List also visible on Morphemes.
> #984: Made tags search multiselect OR rather than AND.

- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_videos.html
An overview for the videos given for example sentences for senses was added to the Videos tab of glosses
I also changed the indentation a little to improve the readability, so there are a little more edits all over the file
> Videos view add sensevideo 963

- signbank/csv_interface.py
- signbank/dictionary/views.py
Removed unused csv update command.
> Added csv create senses to revision history.

- signbank/dictionary/update.py
- signbank/dictionary/views.py
> Added example sentences to revision history

- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/templates/dictionary/try.html
- signbank/dictionary/templatetags/annotation_idgloss_translation.py
- signbank/dictionary/views.py
Some streamlining of the Sense methods so similar methods share code.
To accomplish this, parameters have been added to the methods.
> Prettier and faster

- signbank/dictionary/templates/dictionary/gloss_detail.html
Just some corrections for code that somehow got lost in the process of rewriting parts of it
> Fix for editing and deleting senses #1032

- signbank/dictionary/tests.py
- signbank/dictionary/update.py
Create/Read/Update/Delete and Permission tests for senses.
> Tests for senses

- signbank/dictionary/tests.py
include each other in the similar senses results. Tests method `get_senses_with_similar_sensetranslations_dict` works correctly.
> Test that glosses with similar senses

- signbank/dictionary/tests.py
> Test for no empty translations added by Sense edit

- signbank/dictionary/adminviews.py
- signbank/dictionary/context_data.py
- signbank/dictionary/senses_display.py
- signbank/dictionary/templates/dictionary/admin_senses_list.html
- signbank/dictionary/templates/dictionary/gloss_row.html
- signbank/dictionary/templates/dictionary/sense_row.html
- signbank/dictionary/templates/dictionary/senselist_headerrow.html
- signbank/dictionary/templatetags/annotation_idgloss_translation.py
First part of issue to reduce code redundancy.
> Streamline

- signbank/dictionary/context_data.py
I am slowly compacting code in the get_context_data function.
Work in progress.
> Split get context data functions

- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/dictionary/templates/dictionary/morpheme_detail.html
as is done for Search Panels. Removed excess divs. Problems with Django if-else-endif mismatches so some minor adjustments.
> Make Gloss Detail panels clickable across heading

- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/query_parameters.py
Fixed normalised hasRelationToForeignSign since field values same as other booleans now.
> Fixed multiselect Relation in Query View and hasRelationToForeignSign boolean choice.

- signbank/dictionary/adminviews.py
- signbank/dictionary/context_data.py
- signbank/dictionary/forms.py
- signbank/dictionary/templates/dictionary/admin_gloss_list.html
- signbank/dictionary/templates/dictionary/admin_lemma_list.html
- signbank/dictionary/templates/dictionary/admin_minimalpairs_list.html
- signbank/dictionary/templates/dictionary/admin_morpheme_list.html
- signbank/dictionary/templates/dictionary/admin_senses_list.html
- signbank/query_parameters.py
- signbank/settings/server_specific/default.py
- templates/global-templates/menu.html
as for other search forms. Modified set up of language fields to work if some fields not included. Added missing re.escape to escape of regex input.
> Modified Minimal Pairs and Lemma Search forms

- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/templates/dictionary/admin_minimalpairs_list.html
- signbank/dictionary/templates/dictionary/admin_senses_list.html
- signbank/query_parameters.py
At the moment the changes are primarily removing unused, unreachable code and adding more usage information to the shared functions in `query_parameters.py`
> Streamline code

- signbank/dictionary/templates/dictionary/gloss_detail.html
Time field added as version it tries to find for the video, such that it is never loaded from cache.
> Load videos not from cache #1065

- signbank/abstract_machine.py
- signbank/dictionary/templates/dictionary/virtual_machine.html
- signbank/dictionary/templates/dictionary/virtual_machine_api.html
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
API URL to create a gloss.
Plus testing template and signbank url to experiment with using  it, since PyCharm runserver does not have CORS to test it.
The code that implements the create gloss is based on the Import CSV create gloss. (See #1162.)
See #1152.
> API Create Gloss

- signbank/abstract_machine.py
- signbank/dictionary/templates/dictionary/virtual_machine_api.html
Keep them in English for the API to match CSV headers.
Added csrf except to api url.
> #1187, #1152, #1182: Fixed bug related to translations of gloss fields.

- signbank/api_interface.py
- signbank/dictionary/models.py
- signbank/dictionary/views.py
- signbank/tools.py
Or whatever the language code is in the request, if available, otherwise English (default).
This is on signbank-dev.
The API function retrieves the user and the language code from the request.
> #1212: Return gloss fields and field values in Dutch

- signbank/dictionary/templates/dictionary/virtual_machine_gloss_update_api.html
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
- signbank/gloss_update.py
This implements the gloss fields of #1202.
This is on branch api_interface
This is deployed on signbank-dev
@Jetske maybe you can merge this into your branch where you're working on update senses?
Or do 
`git cherry-pick  <commit-reference>`
on the commits in this branch to merge them into your branch.
> Api interface update gloss

- signbank/abstract_machine.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/forms.py
- signbank/dictionary/management/commands/add_user_affiliation_to_glosses.py
- signbank/dictionary/update.py
- signbank/dictionary/views.py
> #1211: Automatically add affiliation of user to new glosses

- signbank/gloss_update.py
- signbank/registration/templates/user_profile.html
Added translation for user profile #1235
> #1236: Fixed False update value for API processing

- signbank/api_interface.py
- signbank/dictionary/models.py
- signbank/dictionary/update_csv.py
- signbank/gloss_update.py
> #1225: Added Notes to package API json retrieval for

- signbank/dictionary/templates/dictionary/add_annotated_sentence.html
- signbank/dictionary/templates/dictionary/edit_annotated_sentence.html
- signbank/dictionary/templates/dictionary/gloss_detail.html
- signbank/video/views.py
@susanodd  I just added the necessary tags for translating the pages, however I have never done this before and don't know how to make new .po files. Can you check my last commit? It that looks ok this is ready to merge.
> Annotated sentence improvements #1234

- signbank/dictionary/models.py
- signbank/video/views.py
Galya had problems with video uploads. I hope this fixes it. At least it will give a neat error message if it still fails.
> Fix for other temporary file types #1234

- signbank/dictionary/update_csv.py
and fields implemented as related objects are updated.
> #1292: Update gloss timestamp when morphology fields

- signbank/dictionary/views.py
- signbank/tools.py
> #1108: Do not use MAGIC, just report unrecognised

- signbank/api_interface.py
- signbank/dictionary/models.py
- signbank/dictionary/update.py
- signbank/dictionary/urls.py
- signbank/dictionary/views.py
- signbank/gloss_update.py
This on `signbank-test`
Base64 encoding is used for the video because
1. that's what javascript uses once put in a buffer
2. the file is passed inside of a json data structure which needs to be JSON.stringified
3. this is working
TO DO
Add to API Wiki
> Non manuele elementen API

- signbank/dictionary/views.py
- signbank/settings/server_specific/default.py
- signbank/settings/server_specific/global_sb_new_aj.py
> Gloss lookup changed #1349

- signbank/dataset_checks.py
- signbank/dictionary/dataset_views.py
- signbank/dictionary/templates/dictionary/admin_dataset_manager.html
- signbank/dictionary/templates/dictionary/dataset_consistency_checks.html
- signbank/dictionary/tests.py
- signbank/urls.py
- This is on signbank-susan
- It is accessible from the Dataset Manager page as a button for the dataset which goes to the new page
> #1361: View video paths dataset manager

- signbank/dictionary/admin.py
- signbank/dictionary/adminviews.py
- signbank/dictionary/models.py
- signbank/video/admin.py
- signbank/video/models.py
Show video and eaf file and timestamps in admin
> #1370: Admin and Video Admin for Annotated Sentences/Videos

- signbank/dataset_checks.py
- signbank/dictionary/dataset_views.py
when they have the wrong bak bak names.
this will end up in a different place in the code. It's not clear how much feedback will be needed or how long it will take to run.
> #1373: Imperative function with side effects to rename video files

- signbank/dictionary/templates/dictionary/update_lemma.html
- signbank/dictionary/update.py
- signbank/dictionary/urls.py
The trash icon shows for archived gloss in the "update lemma" page accessible via the "show all lemmas"
> #1375: Trash button in Lemma Update for gloss deletion.

- signbank/dictionary/admin.py
These are read-only and harmless
> #1395: Search in video history and revision history in admin

- signbank/dictionary/models.py
- signbank/dictionary/templates/dictionary/admin_dataset_list.html
- signbank/dictionary/tests.py
- signbank/settings/server_specific/asl_yale.py
- signbank/settings/server_specific/default.py
- signbank/settings/server_specific/global_sb_new_aj.py
- signbank/tools.py
All the tests pass after adding the absolute path setting.
Here is a screenshot of what the new column looks like:
> #1411: Allow to download ECV file.

- signbank/video/management/commands/convertvideo.py
PyCharm was flagging this as an error
> #1390: Removed syntax error from very old command

- signbank/dictionary/adminviews.py
- signbank/dictionary/templates/dictionary/related_signs_detail_view.html
- signbank/tools.py
Links in sequential morphology in relations view
> #1437: Repaired sequential and compound morphology display

- signbank/dictionary/views.py
#1403, #1419, #1430: Copied fixes to public view protected media to its own branch.
Since links to the new video types are already being used publically.
<details>
When they're ready, the new perspective NME video paths will also need to be added.
I'm certain the code of the pattern matching function on filenames can be made fancier, but it works as it is.
Dit is recht toe recht aan.
> Fixes to public view protected media for new video types

- signbank/dictionary/templates/dictionary/gloss.html
1. Show annotated sentences
2. Public view, if panel is empty show space when header is clicked.
> #1403: Public view more info

- docs/signbank-api.json
> #1475: Swagger spec for upload gloss image.

- signbank/api_interface.py
- signbank/dictionary/models.py
- signbank/tools.py
This pull request extends the ``gloss_data`` endpoint with two things:
* An overview of perspective videos available for a gloss
* For the main video, perspective videos and nme_video, it provides and MD5 checksum, so you can quickly compare the file online with the video you might have on disk locally without downloading the file.
The endpoint returns this:
```json
{
"4483": {
"Lemma ID Gloss: Dutch": "WESSELTEST",
"Lemma ID Gloss: English": "WESSELTEST",
"Annotation ID Gloss: Dutch": "wesseltest11",
"Annotation ID Gloss: English": "wesseltest11",
"Handedness": "1",
"Strong Hand": "A",
"Strong Hand Letter": "True",
"Location": "Belly > chest",
"In The Web Dictionary": "False",
"Is This A Proposed New Sign?": "False",
"Exclude From Ecv": "True",
"Relation Between Articulators": "Below", …
```
> Extended gloss data endpoint with perspective videos and checksums

- signbank/dictionary/tests.py
Make tests create form data depending on OBLIGATORY_FIELDS setting
This was not working on the development server where this is non-empty.
I had added the number and letter options to the obligatory fields but had not put this in the tests.
This applies to non-empty OBLIGATORY FIELDS
> Fixed tests create gloss data form setup to depend on OBLIGATORY_FIELDS

- signbank/video/admin.py
- signbank/video/convertvideo.py
and another in pattern match group, needed the dot for functionality
This applies to Gloss Video Admin, for searching on non-MP4 file types
> Bug Fix: filetype bug in string comparison

- signbank/dictionary/adminviews.py
as per solution @vanlummelhuizen
Totally obscure, but it works!!
A confirm popup appears. No idea where that comes from. It looks different than the ones we program into the templates.
> #1552: rename class method in LemmaDeleteView to form_valid

- requirements.txt
- signbank/registration/forms.py
This was flagged by de security bot #1567
> Removed django-select2 as it was not being used.

- signbank/dictionary/models.py
> Use mixin class for class meta methods
